module.exports = {
  CREATE_SPENDING: 'CREATE_SPENDING',
  ALL_SPENDINGS: 'ALL_SPENDINGS',
  UPDATE_SPENDING: 'UPDATE_SPENDING',
  REMOVE_SPENDING: 'REMOVE_SPENDING',
  REMOVE_SPENDINGS: 'REMOVE_SPENDINGS',
  CURRENT_SPENDINGS: 'CURRENT_SPENDINGS'
}
